#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 7002 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-config-eureka02
    
eureka:
  instance:
    hostname: eurekaServer02.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eurekaServer01.com:7001/eureka/,http://eurekaServer03.com:7003/eureka/
security:
  basic:
    enabled: false
---
server:
  port: 7002 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-eureka02

eureka:
  instance:
    hostname: eurekaServer02.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eurekaServer01.com:7001/eureka/,http://eurekaServer03.com:7003/eureka/
security:
  basic:
    enabled: false
    
#保存时注意，选择 UTF-8 保存